---
# --------------------------------

- name: "Install pre-requisites"
  ansible.builtin.apt:
    name: "{{ sui_pkg_dependencies }}"
    state: present
    update_cache: true
  become: true
  tags: [ct-sui]

- name: "Add runtime user"
  ansible.builtin.user:
    name: "{{ sui_username }}"
    shell: /bin/bash
  become: true
  tags: [ct-sui]

- name: "Create directories"
  ansible.builtin.file:
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    name: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
  loop: "{{ sui_directories }}"
  become: true
  tags: [ct-sui]

# --------------------------------
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o install-rust.sh
# rustup update stable
# git clone https://github.com/cabtech/sui.git
# cd sui
# git remote add upstream https://github.com/MystenLabs/sui
# git fetch upstream
# git checkout --track upstream/testnet
# cp crates/sui-config/data/fullnode-template.yaml fullnode.yaml
# curl -fLJO https://github.com/MystenLabs/sui-genesis/raw/main/testnet/genesis.blob
# set path to genesis block and DB in fullnode.yaml
# cargo build --release --bin sui
# cargo run --release --bin sui-node -- --config-path fullnode.yaml
# TODO
# Systemd unit file
# --------------------------------
...
